- name: Prepare host to install ceph VM
  hosts: localhost
  gather_facts: False
  remote_user: {{ user }}

  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
    
  tasks:
    - name : Test
      debug: msg="Test"
    

