- name: Prepare host for Ceph lab
  hosts: localhost
  gather_facts: False

  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
    
  tasks:
    - name : Backup sudoers file for safety
      command : cp -f /etc/sudoers /etc/sudoers.bak

    - name : Create sudoers temporary file 
      command : cp -f /etc/sudoers /etc/sudoers.tmp


    - name : Enable password-less sudo
      lineinfile : "dest=/etc/sudoers.tmp  
                   state=present 
                   regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL' 
                   validate='visudo -c -q -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers'"

      
